Use 'vim-reset' to trigger the reset

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -44,6 +44,89 @@ normalize() {
   pwd
 }
 
+vim_reset() {
+    if check_vim_reset
+    then
+        return 1
+    fi
+
+    VIM=$( which vim )
+    [[ -z ${VIM} ]] && {
+        echo "No VIM installed?"
+        return 1
+    }
+    GVIM=$( which gvim )
+    [[ -z ${GVIM} ]] && {
+        GVIM=${VIM}
+    }
+
+    if [[ -z ${VIM_RESET_CONFDIR} ]]
+    then
+        echo "Env-variable 'VIM_RESET_CONFDIR' has to be set" >&2
+        echo "Aborting..."
+        return 1
+    else
+        echo "Using ${VIM_RESET_CONFDIR}" >&2
+    fi
+
+    if [[ -z ${VIM_RESET_VIMRC} ]]
+    then
+        VIM_RESET_VIMRC=${VIM_RESET_CONFDIR}/_vimrc
+    fi
+
+    if [[ -z ${VIM_RESET_GVIMRC} ]]
+    then
+        VIM_RESET_GVIMRC=${VIM_RESET_CONFDIR}/_gvimrc
+    fi
+
+    if [[ -n ${VIM_RESET_VIMRTP} ]]
+    then
+        VIM_RESET_VIMRTP=${VIM_RESET_CONFDIR},${VIM_RESET_VIMRTP}
+    else
+        VIM_RESET_VIMRTP=${VIM_RESET_CONFDIR}
+    fi
+
+    VIM_RESET_VIMRTP=${VIM_RESET_VIMRTP},"~/.vim"
+
+    declare -a rtps
+    IFS=',' read -ra rtps < <(unset IFS;echo ${VIM_RESET_VIMRTP})
+
+    declare -a _rtps
+    IFS=',' read -ra _rtps < <(get_vim_rtp)
+
+    for rtp_i in ${!rtps[*]}
+    do
+        # Preserve the exact order of the rtps
+        rtp=${rtps[$((${#rtps[@]} - ${rtp_i} - 1))]}
+
+        # Skip non-directory path
+        [[ -d ${rtp} ]] || continue
+
+        # Remove duplicate paths
+        for _rtp_i in ${!_rtps[*]}
+        do
+            _rtp=${_rtps[${_rtp_i}]}
+            {
+                [[ ${rtp%/} == ${_rtp%/} ]] || \
+                    [[ ${rtp%/}/after == ${_rtp%/} ]]
+            } && {
+                unset _rtps[${_rtp_i}]
+            }
+        done
+        [[ ${rtp} == "~/.vim" ]] && continue
+        _rtps=( "${rtp}" "${_rtps[@]}" "${rtp}"/after )
+    done
+    VIM_RESET_VIMRTP=$( IFS=","; echo "${_rtps[*]}" )
+
+    echo "========================"
+    echo "VIMRC=${VIM_RESET_VIMRC}"
+    echo "GVIMRC=${VIM_RESET_GVIMRC}"
+    echo "VIMRTP=${VIM_RESET_VIMRTP}"
+    echo "========================"
+
+    hijack_vim || return 1
+}
+
 hijack_vim() {
     if [[ ! -d ${VIM_RESET_CONFDIR} ]]
     then
@@ -118,84 +201,4 @@ check_vim_reset() {
     grep -IF 'GENERATED_BY_VIM_RESET' "$( which vim )" &>/dev/null
 }
 
-if check_vim_reset
-then
-    return 1
-fi
-
-VIM=$( which vim )
-[[ -z ${VIM} ]] && {
-    echo "No VIM installed?"
-    return 1
-}
-
-GVIM=$( which gvim )
-[[ -z ${GVIM} ]] && {
-    GVIM=${VIM}
-}
-
-if [[ -z ${VIM_RESET_CONFDIR} ]]
-then
-    echo "Env-variable 'VIM_RESET_CONFDIR' has to be set" >&2
-    echo "Aborting..."
-    return 1
-else
-    echo "Using ${VIM_RESET_CONFDIR}" >&2
-fi
-
-if [[ -z ${VIM_RESET_VIMRC} ]]
-then
-    VIM_RESET_VIMRC=${VIM_RESET_CONFDIR}/_vimrc
-fi
-
-if [[ -z ${VIM_RESET_GVIMRC} ]]
-then
-    VIM_RESET_GVIMRC=${VIM_RESET_CONFDIR}/_gvimrc
-fi
-
-if [[ -n ${VIM_RESET_VIMRTP} ]]
-then
-    VIM_RESET_VIMRTP=${VIM_RESET_CONFDIR},${VIM_RESET_VIMRTP}
-else
-    VIM_RESET_VIMRTP=${VIM_RESET_CONFDIR}
-fi
-
-VIM_RESET_VIMRTP=${VIM_RESET_VIMRTP},"~/.vim"
-
-declare -a rtps
-IFS=',' read -ra rtps < <(unset IFS;echo ${VIM_RESET_VIMRTP})
-
-declare -a _rtps
-IFS=',' read -ra _rtps < <(get_vim_rtp)
-
-for rtp_i in ${!rtps[*]}
-do
-    # Preserve the exact order of the rtps
-    rtp=${rtps[$((${#rtps[@]} - ${rtp_i} - 1))]}
-
-    # Skip non-directory path
-    [[ -d ${rtp} ]] || continue
-
-    # Remove duplicate paths
-    for _rtp_i in ${!_rtps[*]}
-    do
-        _rtp=${_rtps[${_rtp_i}]}
-        {
-            [[ ${rtp%/} == ${_rtp%/} ]] || \
-                [[ ${rtp%/}/after == ${_rtp%/} ]]
-        } && {
-            unset _rtps[${_rtp_i}]
-        }
-    done
-    [[ ${rtp} == "~/.vim" ]] && continue
-    _rtps=( "${rtp}" "${_rtps[@]}" "${rtp}"/after )
-done
-VIM_RESET_VIMRTP=$( IFS=","; echo "${_rtps[*]}" )
-
-echo "========================"
-echo "VIMRC=${VIM_RESET_VIMRC}"
-echo "GVIMRC=${VIM_RESET_GVIMRC}"
-echo "VIMRTP=${VIM_RESET_VIMRTP}"
-echo "========================"
-
-hijack_vim || return 1
+alias vim-reset=vim_reset
